#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap: install pinned DSH, isolate DSH_HOME,
# link this checkout into the web profile for live plugin development.
set -euo pipefail

DSH_VERSION="0.1.0-rc.6"
DSH_HOME_DEFAULT="${HOME}/.dsh-cloud"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

prefer_node_path() {
	if [[ -n ${NVM_BIN:-} && -x ${NVM_BIN}/node ]]; then
		printf '%s\n' "$NVM_BIN"
		return
	fi
	local candidate
	for candidate in \
		"${HOME}/.nvm/versions/node/v22.22.2/bin" \
		"${HOME}/.nvm/versions/node/v22.19.0/bin"; do
		if [[ -x ${candidate}/node ]]; then
			printf '%s\n' "$candidate"
			return
		fi
	done
	printf '%s\n' "$(dirname "$(command -v node)")"
}

NODE_BIN="$(prefer_node_path)"
export PATH="${NODE_BIN}:${PATH}"

if ! command -v node >/dev/null; then
	echo "error: node is required to install @deepseek-ai/dsh@${DSH_VERSION}" >&2
	exit 1
fi

node_major="$(node -p 'process.versions.node.split(".")[0]')"
node_minor="$(node -p 'process.versions.node.split(".")[1]')"
if (( node_major < 22 || (node_major == 22 && node_minor < 19) )); then
	echo "error: Node.js ^22.19.0 || >=24 is required (found $(node -v))" >&2
	exit 1
fi

if ! command -v pnpm >/dev/null; then
	npm install --global pnpm@11.21.0
fi

npm install --global "@deepseek-ai/dsh@${DSH_VERSION}"

export DSH_HOME="${DSH_HOME:-$DSH_HOME_DEFAULT}"
mkdir -p "$DSH_HOME"
chmod 700 "$DSH_HOME"

ENV_FILE="${DSH_HOME}/env.sh"
cat >"$ENV_FILE" <<EOF
# Generated by .cursor/install-cloud-dsh.sh — source from your shell.
export DSH_HOME="${DSH_HOME}"
export PATH="${NODE_BIN}:\$PATH"
EOF

if [[ -f ${HOME}/.bashrc ]]; then
	marker="# cloud-agent-dsh-env"
	if ! grep -Fq "$marker" "${HOME}/.bashrc"; then
		{
			printf '\n%s\n' "$marker"
			printf '[ -f %q ] && . %q\n' "$ENV_FILE" "$ENV_FILE"
		} >>"${HOME}/.bashrc"
	fi
fi

# Materialize the web profile (auto-init) without binding a port.
dsh --profile web --dump-default-config >/dev/null

cd "$REPO_ROOT"
pnpm install --frozen-lockfile

# Link the checkout so Settings / OAuth routes pick up local lib/ changes after rebuild.
dsh plugin --profile web add "$REPO_ROOT"

echo "cloud dsh ready: DSH_HOME=${DSH_HOME} dsh=$(dsh -V 2>/dev/null || true)"
echo "start UI when needed: dsh web --host 127.0.0.1 --port 18180"
